apiVersion: apps/v1
kind: Deployment  
metadata:
  name: frontend-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: aakashshinde09/angular_pipeline:frontend
        ports:
        - name: angular
          containerPort: 30080
          protocol: TCP 
