apiVersion: v1 
kind: Service 
metadata: 
  name: backend-service
spec: 
  selector: 
    app: backend-app 
  ports: 
  - name: spring
    targetPort: 30090
    port: 30090
    nodePort: 30090
  type: NodePort
