apiVersion: v1 
kind: Service 
metadata: 
  name: backend-service
spec: 
  selector: 
    app: backend-app 
  ports: 
  - name: springboot-tomcat 
    targetPort: 8085
    port: 8085
  type: ClusterIP
